#!/usr/bin/env bash
# Display /etc/passwd in story format
while IFS=: read -r user pass uid gid name home shell; do echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $name"; done < /etc/passwd
