#!/usr/bin/env bash
# Display visitors grouped by IP and HTTP code
awk '{counts[$1" "$9]++} END {for (combo in counts) print counts[combo], combo}' apache-access.log | sort -rn | awk '{print $1" "$2" "$3}'
