#!/usr/bin/env bash
# Processes any input log file, groups IP/Status, sorts, and strips whitespace
awk '{c[$1" "$9]++} END {for (k in c) print c[k], k}' "$@" | sort -k1,1nr -k2,2 -k3,3 | awk '{$1=$1;print}'
